services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"  
    depends_on:
      - backend  
    env_file: 
      - ./frontend/.env
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - ./backend/.env